


DROP TABLE IF EXISTS desafio_curadoria."TB_PACIENTE";

DROP SEQUENCE IF EXISTS desafio_curadoria."SEQ_TB_PACIENTE_ID";


DROP TABLE IF EXISTS desafio_curadoria."TB_ESTABELECIMENTO";

DROP SEQUENCE IF EXISTS desafio_curadoria."SEQ_TB_ESTABELECIMENTO_ID";
